default: &default
  adapter: postgresql
  encoding: unicode
  username: "<%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>"
  host: "<%= ENV.fetch('DATABASE_HOSTNAME', 'localhost') %>"
  port: "<%= ENV.fetch('DATABASE_PORT', 5432) %>"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: "<%= ENV.fetch('DATABASE_NAME', 'etd_development') %>"
  queue:
    <<: *default
    database: "<%= ENV.fetch('DATABASE_QUEUE_NAME', 'etd_development_queue') %>"
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: "<%= ENV.fetch('DATABASE_CACHE_NAME', 'etd_development_cache') %>"
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: "<%= ENV.fetch('DATABASE_CABLE_NAME', 'etd_development_cable') %>"
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: "<%= ENV.fetch('DATABASE_NAME', 'etd_test') %>"

production:
  primary:
    <<: *default
    database: "<%= ENV.fetch('DATABASE_NAME', 'etd_production') %>"
  queue:
    <<: *default
    database: "<%= ENV.fetch('DATABASE_QUEUE_NAME', 'etd_production_queue') %>"
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: "<%= ENV.fetch('DATABASE_CACHE_NAME', 'etd_production_cache') %>"
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: "<%= ENV.fetch('DATABASE_CABLE_NAME', 'etd_production_cable') %>"
    migrations_paths: db/cable_migrate
