---
engine_version: 0.4.37
file_version: 2025-08-08 22:27:53.723256000 Z
resources: []
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2025-08-08 21:38:20.695272000 +00:00
queries:
- id: 1
  name: Submissions
  sql_body: SELECT * FROM submissions
  description:
  preferences:
    query_type: sql
    database: primary
    visualization: table
    visualization_options: {}
    variables: []
    api_config_name: origin
  tags: []
  updated_at: 2025-08-08 21:58:25.490612000 +00:00
- id: 2
  name: Registered
  sql_body: SELECT * FROM submissions where submission_state = 'registered'
  description: Submissions that are in a registered state have not yet been submitted
  preferences:
    query_type: sql
    database: primary
    visualization: table
    visualization_options: {}
    variables: []
  tags: []
  updated_at: 2025-08-08 22:20:48.489964000 +00:00
dashboards:
- id: 1
  title: Registered
  description:
  preferences:
    layout:
    - title: Registered
      query_id: 2
      size: 3x2
    variables: []
  tags: []
  updated_at: 2025-08-08 22:27:06.639847000 +00:00
- id: 2
  title: Dashboard
  description:
  preferences:
    layout:
    - title: Registered
      query_id: 2
      size: 3x2
    variables: []
  tags: []
  updated_at: 2025-08-08 22:27:53.723256000 +00:00
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description:
  updated_at: 2025-08-08 21:38:20.703046000 +00:00
