purl:
  url: "https://sul-purl-stage.stanford.edu"

orcid_base_url: 'https://orcid.org'

datacite:
  prefix: '10.80343'

groups:
  dlss: 'sdr:etds-sul-staff'
  registrar: 'sdr:etds-registrar-staff'
  reports: 'sdr:etds-quarterly-reports'

preview_dir: <%= Rails.root.join('tmp', 'preview').to_s %>

# true to post completed submission to Registrar
dor_submit_ps_xml: false
ps_reg_endpoint: 'http://registrar.example.edu'
ps_reg_username: ~
ps_reg_password: ~
ps_env: 'test'


# ActiveAdmin configs
searchworks_uri: https://searchworks.stanford.edu/view/%<catalog_record_id>s
argo_url: https://argo.stanford.edu
stacks_uri: 'https://stacks.stanford.edu/file/%<druid>s/%<aug_diss_file_name>s'
